In [ ]:
import numpy as np
A1=np.array([1,2,3])
print(A1)

[1 2 3]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(3,)

In [ ]:
A1.size

3

In [ ]:
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [ ]:
A2.shape

(2, 3)

In [ ]:
A2.size

6

In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
A3.shape

(1, 3, 3)

In [ ]:
A3.size

9

In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.ndim

3

In [ ]:
z1=np.zeros(5)
print(z1)

[0. 0. 0. 0. 0.]


In [ ]:
z2=np.zeros(3,dtype=int)
print(z2)

[0 0 0]


In [ ]:
z2.shape

(3,)

In [ ]:
z2.size

3

In [ ]:
z2.ndim

1

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((3,4,5))
z3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((3,1,5),dtype=int)
z3

array([[[0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0]]])

In [ ]:
z3.shape

(3, 1, 5)

In [ ]:
z3.size

15

In [ ]:
z3.ndim

3

In [ ]:
o1=np.ones(5)
o1

array([1., 1., 1., 1., 1.])

In [ ]:
o1=np.ones(5,dtype=int)
o1

array([1, 1, 1, 1, 1])

In [ ]:
o1.shape

(5,)

In [ ]:
o1.size

5

In [ ]:
o1.ndim

1

In [ ]:
o2=np.ones((3,4))
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
o2=np.ones((3,4),dtype=int)
o2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
o2.shape

(3, 4)

In [ ]:
o2.size

12

In [ ]:
o2.ndim

2

In [ ]:
o3=np.ones((2,4,5))
o3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
o3=np.ones((2,4,5),dtype=int)
o3

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
o3.shape

(2, 4, 5)

In [ ]:
o3.size

40

In [ ]:
o3.ndim

3

In [ ]:
f1=np.full(5,5)
f1

array([5, 5, 5, 5, 5])

In [ ]:
f1=np.full(5,5,dtype=float)
f1

array([5., 5., 5., 5., 5.])

In [ ]:
f2=np.full((3,4),5)
f2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
f3=np.full((3,2,4),10)
f3

array([[[10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10]]])